```plantuml
@startuml pot
hide empty description

[*] --> 柱を選択 : 柱ボタン押して柱クリック

state 柱選択中{
    柱を選択 --> グリッドを選択 : グリッド選択ボタン押してグリッドクリック
    state グリッド選択中{
        グリッドを選択 --> タイルを選択 : タイル選択ボタン押してタイルクリック
        state タイル選択中{
           
        }
    }
}

@enduml
```